spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://192.168.88.129:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 070716wzq
  elasticsearch:
    uris: 192.168.88.129:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost
  enableInnerLog: false
